name: Build Linux Container Image and Push to ACR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: dotnet
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: 1650706003dockerworkshop.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t 1650706003dockerworkshop.azurecr.io/shinchanapp:${{ github.sha }}
        docker push 1650706003dockerworkshop.azurecr.io/shinchanapp:${{ github.sha }}
