# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - 1650706003-dockerworkshop

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://1650706003dockerworkshop.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_663c5a0c3e2446a6ac8f35cf10db3356 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_349ff87cf9704536901d2d9cf86a988e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: 1650706003dockerworkshop.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_663c5a0c3e2446a6ac8f35cf10db3356 }}/shinchanapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: '1650706003-dockerworkshop'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_489e52d815de4e87a78a90fead3b055a }}
        images: '1650706003dockerworkshop.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_663c5a0c3e2446a6ac8f35cf10db3356 }}/shinchanapp:${{ github.sha }}'